name: Node CI

on: [push, workflow_dispatch]

env:
  IMAGE_NAME: docker.pkg.github.com/navikt/start-samtale/start-samtale
  TZ: Europe/Amsterdam 
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      PRINT_PAYLOAD: true

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create image tag
        run: echo "IMAGE=${IMAGE_NAME}:$(echo ${{ github.ref }} | cut -d '/' -f3).$(date '+%F-%H%M').$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV #eks pa tag  gh-actions.2020-01-08-1255.8fa4236
      - run: npm ci
      - run: npm run test
      - run: npm run build

      - name: Build and publish Docker image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker build -t ${IMAGE} .
          docker push ${IMAGE}

      - name: deply q1 sbs
        if: github.ref == 'refs/heads/dev'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-sbs
          RESOURCE: nais-q.yaml
          VAR: namespace=q1

      - name: deply prod sbs
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-sbs
          RESOURCE: nais.yaml
